spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
    url: jdbc:mysql://localhost:3306/inventory_service_db
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
